interface event-handler {
  use dandelion:common/values@0.1.0.{value-map};
  use timers.{event-id};

  record load-event {
    configuration: value-map,
  }

  record tick-event {
    id: event-id,
  }

  variant event {
    load(load-event),
    tick(tick-event),
  }

  on-event: func(e: event);
}
