interface event-handler {
  use dandelion:common/types@0.1.0.{value-map};

  record load-event {
    configuration: value-map,
  }

  record tick-event {
    event-id: u32,
  }

  variant event {
    load(load-event),
    tick(tick-event),
  }

  on-event: func(e: event);
}
