interface event-handler {
  use timers.{event-id, monotonic-instant};

  record tick-event {
    id: event-id,
    now: monotonic-instant,
  }

  variant event {
    load,
    tick(tick-event),
  }

  on-event: func(ev: event) -> result;
}
