interface timers {
  use dandelion:common/monotonic-clocks@0.1.0.{monotonic-duration, monotonic-instant};

  type event-id = u32;

  resource timer {
    constructor(tick-at: monotonic-instant, id: event-id);
    cancel: func() -> result;
  }
}
