interface leases {
  use types.{instant};

  type lease-id = u32;

  create-lease: func(expires-at: instant) -> result<lease-id>;
  update-lease: func(id: lease-id, expires-at: instant) -> result;
  expire-lease: func(id: lease-id) -> result;
  get-lease: func(id: lease-id) -> result<instant>;
}
